### ISSUE TITLE
タスクリストの作成

### ISSUE THREAD

**Issue by Johnkawa** [Johnkawa/HotelSearchForIOS#18]
# タスクリスト
## TOP画面作成 36h
- TOP画面のビューモデル作成（ホテル情報保持） 1h
### MapView作成 27h
- 画面起動時に現在地周辺地図表示 12h
  - GoogleMapの使い方調査 4h
  - サンプルコード作成および使い方の理解 4h
  - 画面起動時に現在地周辺地図を表示させる 4h
- 端末の移動に合わせて地図移動 6h
  - Objective-C GoogleMap カメラ 移動 方法　調査 3h
  - 端末の移動に合わせて地図移動 3h
- ホテル位置にマーカー表示 4h
  - Objective-C GoogleMap マーカー 方法　調査 2h
  - ホテル位置にマーカーを表示 2h
- マーカーの吹き出しをタップで詳細画面表示 4h
  - Objective-C 画面遷移 方法　調査 2h
  - マーカーの吹き出しタップ時に詳細画面表示 2h
### ホテルリスト（テーブルビュー）作成 8h
- ホテルリスト（テーブルビュー）作成 4h
- テーブルのセルタップで詳細画面表示 4h
  - テーブルのセルタップイベント処理実装 2h
  - 画面遷移処理実装 2h
### 画面レイアウト作成 4h
- レイアウト作成 4h
### 詳細画面機能実装 19h
- 画面起動時にホテル詳細情報を表示 2h
- 電話アプリ起動 4.5h
  - 電話アプリの起動方法調査 1.5h
  - 実装 3h
- WEBページの表示 4.5h
  - Safariの起動方法調査 1.5h
  - 実装 3h
- メモ（テキスト）を保存する機能実装 2h
- メモ（テキスト）を保存データを元に表示 2h
- 設定画面の表示 2h
- TOP画面の表示 2h
### 画面レイアウト作成 2h
- レイアウト作成 2h
### 設定画面機能実装 6h
- 行ったことがあることを保存する機能実装 2h
- 行ったことがあるかどうかを保存データを元に表示 2h
- 詳細画面表示 2h
### ホテル情報取得API実装 22h

 [楽天トラベル施設情報API](https://webservice.rakuten.co.jp/api/hoteldetailsearch/)
- ~~iOSでWEBAPIを使う方法の調査 8h~~
- ~~テストコード作成およびWEBAPIの使い方の理解 8h~~
- APIのリクエストパラメータクラスの作成 4h
  - 各パラメータのメンバ変数
  - コンストラクタでパラメータを設定
  - URLを作成するメソッド
- APIのリクエストを実行するクラスの作成 10h
  - リクエストパラメータクラスからURLを取得 1h
  - Objective-C http通信 方法　調査 4h
  - リクエストの実行 2h
  - コールバックの実装 2h
  - レスポンスをパースする（パースクラスを呼ぶ） 1h
- APIのレスポンスを解析するクラスの作成 8h
  - Objective-C json パース 方法　調査 4h
  - 受け取ったレスポンスをパース(ビューモデル作成) 4h
### DB 5h
- DB設計 1h
  - Googleスプレッドシートにテーブル設計を記載する
- 保存方法の調査（SQLite） 4h

**Comment by takkumattsu** [comment]
@Johnkawa 
先に #2 を完成させて欲しいです。

**Comment by takkumattsu** [comment]
@Johnkawa
各項目に予定時間を書いておいて欲しいです

**Comment by Johnkawa** [comment]
@TakkuMattsu 
予定時間を追記しました

**Comment by takkumattsu** [comment]
@Johnkawa 

> テストコード作成および使い方の理解 4h

これって具体的にどんな作業ですか？

**Comment by takkumattsu** [comment]
@Johnkawa 

> 端末の移動に合わせて地図移動 4h

これってグーグルマップアプリでいう現在地ボタン押下した時の挙動と同じです？

**Comment by takkumattsu** [comment]
@Johnkawa 

> テストコード作成およびWEBAPIの使い方の理解 8h

これも具体的にどんな作業ですか？

**Comment by Johnkawa** [comment]
@TakkuMattsu 

> テストコード作成および使い方の理解

これは調査のうちの１つです。
実際に簡単なコードを作ってみて動作を見ながらやると理解しやすいので、これを入れました。
マップとWEBAPIはAndroidの時も苦戦して、実際にテストコードを作りながらやっていたので、
今回も同じようにすればいけるかなと思ってます。

> > 端末の移動に合わせて地図移動
> 
> これってグーグルマップアプリでいう現在地ボタン押下した時の挙動と同じです？

はい、同じです。

**Comment by takkumattsu** [comment]
@Johnkawa 

> > テストコード作成および使い方の理解
> 
> これは調査のうちの１つです。
> 実際に簡単なコードを作ってみて動作を見ながらやると理解しやすいので、これを入れました。
> マップとWEBAPIはAndroidの時も苦戦して、実際にテストコードを作りながらやっていたので、
> 今回も同じようにすればいけるかなと思ってます。

なるほど。そうなると、 `GoogleMapの使い方調査 4h` と `テストコード作成および使い方の理解 4h` って同じじゃないですか？

**Comment by takkumattsu** [comment]
@Johnkawa 

> > 端末の移動に合わせて地図移動
> 
> これってグーグルマップアプリでいう現在地ボタン押下した時の挙動と同じです？
> はい、同じです。

了解です。

**Comment by Johnkawa** [comment]
@TakkuMattsu 

> > > テストコード作成および使い方の理解
> > 
> > これは調査のうちの１つです。
> > 実際に簡単なコードを作ってみて動作を見ながらやると理解しやすいので、これを入れました。
> > マップとWEBAPIはAndroidの時も苦戦して、実際にテストコードを作りながらやっていたので、
> > 今回も同じようにすればいけるかなと思ってます。
> 
> なるほど。そうなると、 GoogleMapの使い方調査 4h と テストコード作成および使い方の理解 4h って同じじゃないですか？

`GoogleMapの使い方調査 4h` は情報収集、`テストコード作成および使い方の理解 4h` は実際にやってみて理解を深める、という位置付けで分けています。
本当は二つ合わせて1タスクにしようと思ったのですが、4h では終わらないかなと思い二つに分けました。

**Comment by takkumattsu** [comment]
@Johnkawa 

> GoogleMapの使い方調査 4h は情報収集、テストコード作成および使い方の理解 4h は実際にやってみて理解を深める、という位置付けで分けています。
> 本当は二つ合わせて1タスクにしようと思ったのですが、4h では終わらないかなと思い二つに分けました。

了解です。

**Comment by takkumattsu** [comment]
@Johnkawa 

> ホテル情報取得API実装
> 
> iOSでWEBAPIを使う方法の調査 8h
> テストコード作成およびWEBAPIの使い方の理解 8h

このへんがGoogleMapの実装と差分があるのはなんでですか？
利用するAPIが決まっているのであれば調査時間は8hもかからなそう印象があります。

具体的に細かく言うとどんなタスクがあるのか記載してみてほしい

**Comment by Johnkawa** [comment]
@TakkuMattsu 
Googleマップの部分についてと、各画面から戻る処理についてを更新しましたので、その部分の確認をお願いします。他の部分は以前に見てもらったと認識してます。
Googleマップは軽く調べてみました。その上で調査時間と実装の時間を見積もったので、これでいけると思います。

**Comment by takkumattsu** [comment]
@Johnkawa 

TOP画面作成 36h + 詳細画面作成 23h + 設定画面作成 8h + 共通機能 27h = **94h**

製造だけで約12人日で完了予定と。

これなら終わるという認識で進めます。

**Comment by takkumattsu** [comment]
@Johnkawa 
タスクの洗い出しはこれで任せます。
決めたということはあとはやるだけです。

頑張りましょう。
