### ISSUE TITLE
2016-09-04 打ち合わせ

### ISSUE THREAD

**Issue by takkumattsu** [Johnkawa/HotelSearchForIOS#6]
# 今後の進め方についての打ち合わせ
- 2016/9/4 21:15 〜 21:50
- 参加者
  - 松村
  - 川島
- 自宅（スカイプにて）
## 今後の進め方

設計から始める。それから製造を行う。
実際の開発に入った時に、設計からできないと話についていけない。by松村
## 直近でやること

画面遷移図にメモ画面を追加しよう。製造ではTodoとして未実装でもOK。
実際の画面遷移をできるようになるため。【期限：9/6】by 松村
→画面遷移図を更新します。by 川島

機能一覧を作成しよう。
これがベースとなって設計を行う。【期限：9/6】by 松村
→機能一覧を作成します。by 川島

可能であれば、9/6のもくもく会に参加しよう。
その会の場にて設計について固めましょう。by 松村
→現場の状況次第ですが、参加します。（何もなかったはず）by 川島
# まとめ
- 設計から始める
- 以下を作成する【期限：9/6】
  - 画面遷移図の更新
  - 機能一覧の作成

**Comment by takkumattsu** [comment]
本文部分に以下が書かれていれば議事録として問題ないと思います。

```
# 議事録のタイトル

- YYYY/mm/DD hh:dd 〜 hh:dd
- 参加者
  - A
  - B
- 場所

## 議題

XXXbyA 
→ZZZしますbyB

## 議題2

YYYをする。

# まとめ

- 決まった事
- 決まった事
```

**Comment by takkumattsu** [comment]
@Johnkawa 
↑の内容を↓の鉛筆マークをクリックして **issueの概要** に書いておいてください。

![2016-09-04 21 57 14](https://cloud.githubusercontent.com/assets/3356758/18231122/961abd88-72ea-11e6-80be-5a8a8e2995a1.png)

**Comment by Johnkawa** [comment]
# 今後の進め方についての打ち合わせ
- 2016/9/4 21:15 〜 21:50
- 参加者
  - 松村
  - 川島
- 自宅（スカイプにて）

## 今後の進め方

設計から始める。それから製造を行う。
実際の開発に入った時に、設計からできないと話についていけない。by松村

## 直近でやること

画面遷移図にメモ画面を追加しよう。製造ではTodoとして未実装でもOK。
実際の画面遷移をできるようになるため。【期限：9/6】by 松村
→画面遷移図を更新します。by 川島

機能一覧を作成しよう。
これがベースとなって設計を行う。【期限：9/6】by 松村
→機能一覧を作成します。by 川島

可能であれば、9/6のもくもく会に参加しよう。
その会の場にて設計について固めましょう。by 松村
→現場の状況次第ですが、参加します。（何もなかったはず）by 川島

# まとめ
- 設計から始める
- 以下を作成する【期限：9/6】
  - 画面遷移図の更新
  - 機能一覧の作成

**Comment by takkumattsu** [comment]
↑概要に書いて欲しかった...

**Comment by takkumattsu** [comment]
`No description provided.` ってなっているところ。

**Comment by takkumattsu** [comment]
`ここに書いて欲しかった` って書いてあるのを上書きで更新してください。

**Comment by Johnkawa** [comment]
こんな感じですね！

**Comment by takkumattsu** [comment]
[![LGTM](http://lgtm.in/p/urIWCevWp)](http://lgt

**Comment by takkumattsu** [comment]
@Johnkawa 
**機能一覧の作成** についてissueを作っておいてください。ラベルやマイルストーンは #2 と同じで大丈夫です
