### ISSUE TITLE
機能一覧作成

### ISSUE THREAD

**Issue by Johnkawa** [Johnkawa/HotelSearchForIOS#7]
アプリの機能一覧を作成する。

**Comment by Johnkawa** [comment]
# 機能一覧

## メイン画面
- 現在地周辺の地図表示
  - 画面起動時に表示
  - 端末の移動に合わせて地図更新
  - ホテル位置にピン立て
- 楽天API でホテル情報取得
- ホテルリスト表示
- 電話アプリ起動
  - ホテルの電話番号入力
- ブラウザ起動
  - 楽天のホテル紹介ページ表示
- メモ画面表示

## メモ画面
- 行った事があるか保存
- メモを保存、ホテルの個人的な感想とか

**Comment by Johnkawa** [comment]
マークダウンって見やすいですね、初めて自分から使いました。

**Comment by takkumattsu** [comment]
メモ画面は画面のみの作成で機能は後々実装とする

**Comment by takkumattsu** [comment]
#18 でもっと詳細に記載があるのでこちらはクローズ
